name: flutter_unity_widget_example
description: Demonstrates how to use the flutter_unity_widget plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_unity_widget: ^4.1.0
  mapbox_gl: ^0.11.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  location: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fill/cat_silhouette_pattern.png
    - assets/symbols/custom-icon.png
    - assets/symbols/2.0x/custom-icon.png
    - assets/symbols/3.0x/custom-icon.png
    - assets/style.json
    - assets/sydney.png
    - assets/